In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("https://raw.githubusercontent.com/wtitze/4E/main/netflix_titles.csv")
df

     show_id  ...                                        description
0         s1  ...  As her father nears the end of his life, filmm...
1         s2  ...  After crossing paths at a party, a Cape Town t...
2         s3  ...  To protect his family from a powerful drug lor...
3         s4  ...  Feuds, flirtations and toilet talk go down amo...
4         s5  ...  In a city of coaching centers known to train I...
...      ...  ...                                                ...
8802   s8803  ...  A political cartoonist, a crime reporter and a...
8803   s8804  ...  While living alone in a spooky town, a young g...
8804   s8805  ...  Looking to survive in a world taken over by zo...
8805   s8806  ...  Dragged from civilian life, a former superhero...
8806   s8807  ...  A scrappy but poor boy worms his way into a ty...

[8807 rows x 12 columns]

In [ ]:
df.loc[df["type"].str.contains("TV Show")]

     show_id  ...                                        description
1         s2  ...  After crossing paths at a party, a Cape Town t...
2         s3  ...  To protect his family from a powerful drug lor...
3         s4  ...  Feuds, flirtations and toilet talk go down amo...
4         s5  ...  In a city of coaching centers known to train I...
5         s6  ...  The arrival of a charismatic young priest brin...
...      ...  ...                                                ...
8795   s8796  ...  Now that he's discovered the Pendulum Summonin...
8796   s8797  ...  During the Mongol invasions, Yunus Emre leaves...
8797   s8798  ...  Teen surfer Zak Storm is mysteriously transpor...
8800   s8801  ...  Strong-willed, middle-class Kashaf and carefre...
8803   s8804  ...  While living alone in a spooky town, a young g...

[2676 rows x 12 columns]

In [ ]:
df.loc[df["type"].str.contains("Movie")][["director"]]

                           director
0                   Kirsten Johnson
6     Robert Cullen, José Luis Ucha
7                      Haile Gerima
9                    Theodore Melfi
12              Christian Schwochow
...                             ...
8801                Majid Al Ansari
8802                  David Fincher
8804                Ruben Fleischer
8805                   Peter Hewitt
8806                    Mozez Singh

[6131 rows x 1 columns]

In [ ]:
df.loc[df["description"].str.contains("party")]

     show_id  ...                                        description
1         s2  ...  After crossing paths at a party, a Cape Town t...
113     s114  ...  Cassie lives to party... until she dies in a f...
146     s147  ...  After Kid gets engaged, Play plans to throw th...
655     s656  ...  After a painful breakup, a trio of party-lovin...
679     s680  ...  After a traumatic incident at a party makes he...
...      ...  ...                                                ...
8173   s8174  ...  From controversial cartoonist to powerful Mumb...
8335   s8336  ...  A hard-partying heir dons a disguise to fight ...
8367   s8368  ...  A man accepts an invitation to a dinner party ...
8782   s8783  ...  With an all-important high school party at sta...
8799   s8800  ...  A change in the leadership of a political part...

[76 rows x 12 columns]

In [ ]:
df['release_year'].value_counts().idxmin()

1959

In [ ]:
df[df["director"].isnull()]

     show_id  ...                                        description
1         s2  ...  After crossing paths at a party, a Cape Town t...
3         s4  ...  Feuds, flirtations and toilet talk go down amo...
4         s5  ...  In a city of coaching centers known to train I...
10       s11  ...  Sicily boasts a bold "Anti-Mafia" coalition. B...
14       s15  ...  Cameras following Bengaluru police on the job ...
...      ...  ...                                                ...
8795   s8796  ...  Now that he's discovered the Pendulum Summonin...
8796   s8797  ...  During the Mongol invasions, Yunus Emre leaves...
8797   s8798  ...  Teen surfer Zak Storm is mysteriously transpor...
8800   s8801  ...  Strong-willed, middle-class Kashaf and carefre...
8803   s8804  ...  While living alone in a spooky town, a young g...

[2634 rows x 12 columns]

In [ ]:
df.groupby("country").count().sort_values(["show_id"], ascending = False)[["show_id"]]

                                                    show_id
country
United States                                          2818
India                                                   972
United Kingdom                                          419
Japan                                                   245
South Korea                                             199
...                                                     ...
Ireland, Canada, Luxembourg, United States, Uni...        1
Ireland, Canada, United Kingdom, United States            1
Ireland, Canada, United States, United Kingdom            1
Ireland, France, Iceland, United States, Mexico...        1
Zimbabwe                                                  1

[748 rows x 1 columns]

In [ ]:
df['country'].value_counts()[df['country'].value_counts() > 14]

United States                    2818
India                             972
United Kingdom                    419
Japan                             245
South Korea                       199
Canada                            181
Spain                             145
France                            124
Mexico                            110
Egypt                             106
Turkey                            105
Nigeria                            95
Australia                          87
Taiwan                             81
Indonesia                          79
Brazil                             77
Philippines                        75
United Kingdom, United States      75
United States, Canada              73
Germany                            67
China                              66
Thailand                           61
Argentina                          56
Hong Kong                          53
United States, United Kingdom      47
Italy                              45
Canada, United States              45
Colombia                           35
South Africa                       30
France, Belgium                    27
Poland                             24
Singapore                          23
Malaysia                           22
Netherlands                        19
Pakistan                           18
United States, Germany             17
Hong Kong, China                   16
United States, Japan               16
United States, France              16
Lebanon                            15
Russia                             15
Name: country, dtype: int64

In [ ]:
df.country.value_counts()[df.country.value_counts()==df.country.value_counts().max()]

United States    2818
Name: country, dtype: int64

In [ ]:
df.drop(['rating'], axis = 1)

     show_id  ...                                        description
0         s1  ...  As her father nears the end of his life, filmm...
1         s2  ...  After crossing paths at a party, a Cape Town t...
2         s3  ...  To protect his family from a powerful drug lor...
3         s4  ...  Feuds, flirtations and toilet talk go down amo...
4         s5  ...  In a city of coaching centers known to train I...
...      ...  ...                                                ...
8802   s8803  ...  A political cartoonist, a crime reporter and a...
8803   s8804  ...  While living alone in a spooky town, a young g...
8804   s8805  ...  Looking to survive in a world taken over by zo...
8805   s8806  ...  Dragged from civilian life, a former superhero...
8806   s8807  ...  A scrappy but poor boy worms his way into a ty...

[8807 rows x 11 columns]

In [ ]:
df = df.drop(df[df['listed_in'].str.contains("Crime TV")].index)
df

     show_id  ...                                        description
0         s1  ...  As her father nears the end of his life, filmm...
1         s2  ...  After crossing paths at a party, a Cape Town t...
3         s4  ...  Feuds, flirtations and toilet talk go down amo...
4         s5  ...  In a city of coaching centers known to train I...
5         s6  ...  The arrival of a charismatic young priest brin...
...      ...  ...                                                ...
8802   s8803  ...  A political cartoonist, a crime reporter and a...
8803   s8804  ...  While living alone in a spooky town, a young g...
8804   s8805  ...  Looking to survive in a world taken over by zo...
8805   s8806  ...  Dragged from civilian life, a former superhero...
8806   s8807  ...  A scrappy but poor boy worms his way into a ty...

[8337 rows x 12 columns]

In [ ]:
df.rename(columns={"date_added":' date'},inplace=True)
df

     show_id  ...                                        description
0         s1  ...  As her father nears the end of his life, filmm...
1         s2  ...  After crossing paths at a party, a Cape Town t...
3         s4  ...  Feuds, flirtations and toilet talk go down amo...
4         s5  ...  In a city of coaching centers known to train I...
5         s6  ...  The arrival of a charismatic young priest brin...
...      ...  ...                                                ...
8802   s8803  ...  A political cartoonist, a crime reporter and a...
8803   s8804  ...  While living alone in a spooky town, a young g...
8804   s8805  ...  Looking to survive in a world taken over by zo...
8805   s8806  ...  Dragged from civilian life, a former superhero...
8806   s8807  ...  A scrappy but poor boy worms his way into a ty...

[8337 rows x 12 columns]