In [ ]:
import pymongo 
import pandas as pd

In [ ]:
client = pymongo.MongoClient(
    "mongodb://khaled:33311Ee9@cluster0-shard-00-00.2e0wc.mongodb.net:27017,cluster0-shard-00-01.2e0wc.mongodb.net:27017,cluster0-shard-00-02.2e0wc.mongodb.net:27017/myFirstDatabase?ssl=true&replicaSet=atlas-3iutc4-shard-0&authSource=admin&retryWrites=true&w=majority")
db = client.Elshahat

In [ ]:
df = db.consolati_italiani.find_one()
df

{'_id': ObjectId('623d88bd7dd56dbed7429f53'),
 'capomissione': 'DE RIU ANTONELLO',
 'continente': 'Asia',
 'email': 'consolato.hongkong@esteri.it',
 'funzionecapo': 'CONSOLE GENERALE',
 'idtiposede': '4',
 'indirizzo': 'Suite 3201, Central Plaza, 18 Harbour Road, Wanchai - Hong Kong',
 'lat': '22.396428',
 'lng': '114.109497',
 'paese': 'REPUBBLICA POPOLARE CINESE',
 'sede': 'CONSOLATO GENERALE - HONG KONG',
 'sitoweb': 'www.conshongkong.esteri.it'}

In [ ]:
df = pd.DataFrame.from_records(db.consolati_italiani.find())
df

,_id,sede,idtiposede,lat,lng,continente,paese,indirizzo,capomissione,funzionecapo,sitoweb,email
0,623d88bd7dd56dbed7429f53,CONSOLATO GENERALE - HONG KONG,4,22.396428,114.109497,Asia,REPUBBLICA POPOLARE CINESE,"Suite 3201, Central Plaza, 18 Harbour Road, Wa...",DE RIU ANTONELLO,CONSOLE GENERALE,www.conshongkong.esteri.it,consolato.hongkong@esteri.it
1,623d88bd7dd56dbed7429f5a,CONSOLATO GENERALE - OSAKA,4,34.6934599,135.496485,Asia,GIAPPONE,"Nakanoshima Festival Tower 17F 2-3-18, Nakanos...",DIODATI LUIGI,CONSOLE GENERALE,www.consosaka.esteri.it,segreteria.osaka@esteri.it
2,623d88bd7dd56dbed7429f44,CONSOLATO GENERALE DI PRIMA CLASSE - ZURIGO,3,47.3689234,8.5326156,Europe,SVIZZERA,"TÃ¶distrasse, 65 - 8002 Zurigo",ALAIMO GIULIO,CONSOLE GENERALE,www.conszurigo.esteri.it,segreteria.zurigo@esteri.it
3,623d88bd7dd56dbed7429f50,CONSOLATO GENERALE - LOS ANGELES (California),4,34.060319,-118.416584,Northern America,STATI UNITI D'AMERICA,"1900 Avenue of the Stars ,Suite 1250, Los Ange...",VERDE ANTONIO,CONSOLE GENERALE,www.conslosangeles.esteri.it,consolato.losangeles@esteri.it
4,623d88bd7dd56dbed7429f52,CONSOLATO GENERALE - BARCELLONA,4,41.3948056,2.1641308,Europe,SPAGNA,"Calle Mallorca, 270 - 08037 Barcellona",DANESE GAIA LUCILLA,CONSOLE GENERALE,www.consbarcellona.esteri.it,segreteria.barcellona@esteri.it
...,...,...,...,...,...,...,...,...,...,...,...,...
446,623d88bd7dd56dbed742a0d2,AGENZIA CONSOLARE ONORARIA - CEFALONIA,12,38.178011,20.4886002,Europe,GRECIA,Od. Stavrou Metaxa 21 - 28100 - ARGOSTOLI,MICHELETTI GRAZIELLA,Agente consolare onorario,NaN,gratsiel@otenet.gr
447,623d88bd7dd56dbed742a0d3,AGENZIA CONSOLARE ONORARIA - SANTORINI,12,36.3990884,25.4477265,Europe,GRECIA,"Messaria, Santorini",PAGONA REKAITI MARIA,Agente consolare onorario,NaN,pamaria@rekaiti.gr
448,623d88bd7dd56dbed742a0e4,AGENZIA CONSOLARE ONORARIA - TOLONE,12,43.136393,5.9101018,Europe,FRANCIA,"391, Avenue des Routes - 83200 Tolone",INSALACO MANTA MARIA,Agente consolare onorario,NaN,tolone.onorario@esteri.it
449,623d88bd7dd56dbed742a0eb,AGENZIA CONSOLARE ONORARIA - BARINAS,12,NaN,NaN,South America,VENEZUELA,"c/c Club Italo Venezolano, Av. 23 de Enero, fr...",GHERARDI PALANGE GIUSEPPE,Agente consolare onorario,NaN,gherardip@gmail.com
450,623d88bd7dd56dbed742a101,AGENZIA CONSOLARE ONORARIA - RIO CUARTO (Cordoba),12,-33.1247691,-64.351341,South America,ARGENTINA,Colon 243 - 5800 Rio Cuarto,BARTOCCIONI ALBERTO GUSTAVO,Agente consolare onorario,NaN,agenciaconsular@hotmail.com

1. il cognome e il nome dei capomissione con la loro funzione

In [ ]:
result=db.consolati_italiani.find({},{"capomissione":1,"_id":0,"funzionecapo":1})
df = pd.DataFrame(list(result))
df

                    capomissione               funzionecapo
0               DE RIU ANTONELLO           CONSOLE GENERALE
1                  DIODATI LUIGI           CONSOLE GENERALE
2                  ALAIMO GIULIO           CONSOLE GENERALE
3                  VERDE ANTONIO           CONSOLE GENERALE
4            DANESE GAIA LUCILLA           CONSOLE GENERALE
..                           ...                        ...
446         MICHELETTI GRAZIELLA  Agente consolare onorario
447         PAGONA REKAITI MARIA  Agente consolare onorario
448         INSALACO MANTA MARIA  Agente consolare onorario
449    GHERARDI PALANGE GIUSEPPE  Agente consolare onorario
450  BARTOCCIONI ALBERTO GUSTAVO  Agente consolare onorario

[451 rows x 2 columns]

2.l'indirizzo del consolato di zurigo

In [ ]:
result=db.consolati_italiani.find({"indirizzo":{"$regex":"Zurigo"}})
df = pd.DataFrame(list(result))
df[['sede','paese','indirizzo']]

,sede,paese,indirizzo
0,CONSOLATO GENERALE DI PRIMA CLASSE - ZURIGO,SVIZZERA,"TÃ¶distrasse, 65 - 8002 Zurigo"

3.l'elenco dei consolati generali.ordinare in ordine alfabetico

In [ ]:
result = db.consolati_italiani.aggregate([{"$unwind": "$sede"},
                              {"$sort":{"sede":-1}}
                              ])

df = pd.DataFrame(list(result))
df

,_id,sede,idtiposede,continente,paese,indirizzo,capomissione,funzionecapo,email,lat,lng,sitoweb
0,623d88bd7dd56dbed742a049,VICE CONSOLATO ONORARIO - WOLLONGONG,11,Oceania,AUSTRALIA,"21, Stewart Street, Wollongong N.S.W. 2500",FERRARI GIOVANNI,Vice Console onorario,lucaferrari@bigpond.com,NaN,NaN,NaN
1,623d88bd7dd56dbed742a0c0,VICE CONSOLATO ONORARIO - WINNIPEG (Manitoba),11,Northern America,CANADA,Caboto Centre 1055 Wilkes Av. Winnipeg Manitob...,CARBONE STANISLAO,Vice Console onorario,mr.carbone@shaw.ca,NaN,NaN,NaN
2,623d88bd7dd56dbed742a06a,VICE CONSOLATO ONORARIO - WINDSOR (Ontario),11,Northern America,CANADA,"635, Erie Street East - Windsor (Ontario) N9A 3Y1",DI SALVO LORENZO MARIO DOMENICO,Vice Console onorario,NaN,NaN,NaN,NaN
3,623d88bd7dd56dbed742a089,VICE CONSOLATO ONORARIO - VOLOS,11,Europe,GRECIA,"Antonopoulou, 45 - 38221 Volos",TSOPELA AIKATERINI,Vice Console onorario,volos.onorario@esteri.it,39.3611528,22.9466828,NaN
4,623d88bd7dd56dbed742a058,VICE CONSOLATO ONORARIO - VISBY,11,Europe,SVEZIA,RAVINSTIGEN 7- 62158 VISBY,ROSSI DIEGO,Vice Console onorario,diego.rossi@havde.org,57.6316374,18.281191,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
446,623d88bd7dd56dbed742a0eb,AGENZIA CONSOLARE ONORARIA - BARINAS,12,South America,VENEZUELA,"c/c Club Italo Venezolano, Av. 23 de Enero, fr...",GHERARDI PALANGE GIUSEPPE,Agente consolare onorario,gherardip@gmail.com,NaN,NaN,NaN
447,623d88bd7dd56dbed742a0d7,AGENZIA CONSOLARE ONORARIA - AALESUND,12,Europe,NORVEGIA,P.O.Box 767 - 6003 Aalesund,AARSETH NILS HELGE,Agente consolare onorario,nha@codfish.no,62.4699084,6.168321,NaN
448,623d88bd7dd56dbed7429f90,AGENZIA CONSOLARE - WOLFSBURG,8,Europe,GERMANIA,Goethestrasse 52 - 38440 Wolfsburg,TARULLO BARBARA,AGENTE CONSOLARE,info.wolfsburg@esteri.it,52.42169,10.78433,www.conswolfsburg.esteri.it/
449,623d88bd7dd56dbed7429f91,AGENZIA CONSOLARE - MORON (Buenos Aires),8,South America,ARGENTINA,Republica Oriental del Uruguay 129 - 1708 Moron,MARINI LAURA,AGENTE CONSOLARE,agenteconsolare.moron@esteri.it,-34.6497096,-58.6176482,www.consmoron.esteri.it
450,623d88bd7dd56dbed7429f92,AGENZIA CONSOLARE - LOMAS DE ZAMORA (Buenos Ai...,8,South America,ARGENTINA,"Avenida Meeks, 701 - 1834 Temperley",MORI TONY,AGENTE CONSOLARE,agentecons.lomas@esteri.it,-34.7699559,-58.3980864,www.conslomasdezamora.esteri.it

In [ ]:
result = db.consolati_italiani.find({"sede":{"$regex":"CONSOLATO GENERALE"}}).sort("sede",1)
df = pd.DataFrame(list(result))
df

,_id,sede,idtiposede,lat,lng,continente,paese,indirizzo,capomissione,funzionecapo,sitoweb,email
0,623d88bd7dd56dbed7429f55,CONSOLATO GENERALE - BAHIA BLANCA (Buenos Aires),4,-38.7116583,-62.262535,South America,ARGENTINA,Avenida AlÃ©m 309 - 8000 BahÃ­a Blanca,PETRARULO ANTONIO,CONSOLE GENERALE (Reggente),www.consbahiablanca.esteri.it,consolato.bahiablanca@esteri.it
1,623d88bd7dd56dbed7429f52,CONSOLATO GENERALE - BARCELLONA,4,41.3948056,2.1641308,Europe,SPAGNA,"Calle Mallorca, 270 - 08037 Barcellona",DANESE GAIA LUCILLA,CONSOLE GENERALE,www.consbarcellona.esteri.it,segreteria.barcellona@esteri.it
2,623d88bd7dd56dbed7429f6f,CONSOLATO GENERALE - BENGASI,4,32.117257,20.06464,Asia,LIBIA,"Shara Amr Ibn El Aas, 105",BEN OMRAN NADIA,COLLABORATORE AMMINISTRATIVO A CONTRATTO,www.consbengasi.esteri.it,conbeng.mail@esteri.it
3,623d88bd7dd56dbed7429f77,CONSOLATO GENERALE - BOSTON (Massachusetts),4,42.3525558,-71.0545882,Northern America,STATI UNITI D'AMERICA,"600 Atlantic Ave. - Boston, MA 02210",DE SANTIS NICOLA,CONSOLE GENERALE,www.consboston.esteri.it,urp.boston@esteri.it
4,623d88bd7dd56dbed7429f4e,CONSOLATO GENERALE - BUENOS AIRES,4,-34.601193,-58.3725789,South America,ARGENTINA,Reconquista 572 - (C1003ABL) Buenos Aires,SMIMMO RICCARDO,CONSOLE GENERALE,www.consbuenosaires.esteri.it,segreteriacg.buenosaires@esteri.it
...,...,...,...,...,...,...,...,...,...,...,...,...
66,623d88bd7dd56dbed7429f9c,CONSOLATO GENERALE ONORARIO - NASSAU,9,25.03428,-77.355413,Northern America,BAHAMAS,NaN,SUIGHI ALBERTO GAETANO,Console Generale onorario,NaN,NaN
67,623d88bd7dd56dbed7429f94,CONSOLATO GENERALE ONORARIO - PORT AU PRINCE,9,NaN,NaN,Northern America,HAITI,"40, Rue Lamarre, B.P. 2120",ABDALLAH SHERIF,Console Generale onorario,NaN,consolato.italia.ht@alsagroup.com
68,623d88bd7dd56dbed7429f93,CONSOLATO GENERALE ONORARIO - REYKJAVIK - HAFN...,9,64.1476368,-21.939247,Europe,ISLANDA,POB 16 - 121 Reykjavik,BJORNSSON PETUR,Console Generale onorario,NaN,consolato@simnet.is
69,623d88bd7dd56dbed7429f99,CONSOLATO GENERALE ONORARIO - TEGUCIGALPA,9,NaN,NaN,Northern America,HONDURAS,NaN,MURRONI ALESSANDRO,Console Generale onorario,NaN,NaN
70,623d88bd7dd56dbed7429f96,CONSOLATO GENERALE ONORARIO - WINDHOEK,9,-22.5888346,17.0621621,Africa,NAMIBIA,"41 von Falkenhausen Street, Pioneespark, Windh...",REBOLDI BLEKS ROSANNA,Console Generale onorario,NaN,rosannareboldi@yahoo.com

In [ ]:
result=db.consolati_italiani.find({},{"sede":1,"_id":0,"paese":1}).sort([("sede", 1)])
df = pd.DataFrame(list(result))
df

                                                  sede      paese
0    AGENZIA CONSOLARE - LOMAS DE ZAMORA (Buenos Ai...  ARGENTINA
1             AGENZIA CONSOLARE - MORON (Buenos Aires)  ARGENTINA
2                        AGENZIA CONSOLARE - WOLFSBURG   GERMANIA
3                AGENZIA CONSOLARE ONORARIA - AALESUND   NORVEGIA
4                 AGENZIA CONSOLARE ONORARIA - BARINAS  VENEZUELA
..                                                 ...        ...
446                    VICE CONSOLATO ONORARIO - VISBY     SVEZIA
447                    VICE CONSOLATO ONORARIO - VOLOS     GRECIA
448        VICE CONSOLATO ONORARIO - WINDSOR (Ontario)     CANADA
449      VICE CONSOLATO ONORARIO - WINNIPEG (Manitoba)     CANADA
450               VICE CONSOLATO ONORARIO - WOLLONGONG  AUSTRALIA

[451 rows x 2 columns]

4.il numero complessivo di consoli generali

In [ ]:
result=db.consolati_italiani.count_documents({"funzionecapo":"CONSOLE GENERALE"})
result

46

5.i consolati che si trovano nell'emisfero australe

In [ ]:
result=db.consolati_italiani.find({"lat":{"$lt":"0"}})
df = pd.DataFrame(list(result))
df

,_id,sede,idtiposede,lat,lng,continente,paese,indirizzo,capomissione,funzionecapo,sitoweb,email
0,623d88bd7dd56dbed7429f43,CONSOLATO GENERALE DI PRIMA CLASSE - SAN PAOLO,3,-23.559803,-46.6578951,South America,BRASILE,"Avenida Paulista, 1963 - 01311-300 San Paolo",PALA MICHELE,CONSOLE GENERALE,www.conssanpaolo.esteri.it,segreteria.sanpaolo@esteri.it
1,623d88bd7dd56dbed7429f82,CONSOLATO - ADELAIDE (Australia Meridionale),6,-34.893746,138.645873,Oceania,AUSTRALIA,"398, Payneham Road - Glynde, S.A. 5070",RONZITTI ROBERTA,CONSOLE,www.consadelaide.esteri.it,consolato.adelaide@esteri.it
2,623d88bd7dd56dbed742a08f,VICE CONSOLATO ONORARIO - CORRIENTES,11,-27.471762,-58.8278205,South America,ARGENTINA,Calle Bolivar n.1839,BRIANTI ROLON CARLOS DOMINGO,Vice Console onorario,NaN,estudiobrianti@gigared.com
3,623d88bd7dd56dbed742a0a6,VICE CONSOLATO ONORARIO - CAMPO GRANDE (Mato G...,11,-20.465283,-54.6179245,South America,BRASILE,"Rua XV de Novembro,253 - Centro - 79002-140 Ca...",TRENTIN ALCIDES,Vice Console onorario,NaN,NaN
4,623d88bd7dd56dbed742a0d8,AGENZIA CONSOLARE ONORARIA - LAS VARILLAS (Cor...,12,-31.8719864,-62.722822,South America,ARGENTINA,Italia 354 - 5940 Las Varillas,LARGHI DOMINGO PAOLO,Agente consolare onorario,NaN,dlarghi@lasvarinet.com.ar
...,...,...,...,...,...,...,...,...,...,...,...,...
85,623d88bd7dd56dbed7429f69,CONSOLATO GENERALE - CURITIBA (ParanÃ ),4,-25.4283563,-49.2732515,South America,BRASILE,"Rua Marechal Deodoro, 630 - 21Â°Andar-Centro C...",FESTA RAFFAELE,CONSOLE GENERALE,www.conscuritiba.esteri.it,segreteria.curitiba@esteri.it
86,623d88bd7dd56dbed7429f8f,CONSOLATO - MAR DEL PLATA,6,-38.0111432,-57.5395984,South America,ARGENTINA,Falucho 1416 - 7600 Mar del Plata,CORTESE DARIO,CONSOLE,www.consmardelplata.esteri.it,segreteria.mardelplata@esteri.it
87,623d88bd7dd56dbed742a04a,VICE CONSOLATO ONORARIO - SOROCABA,11,-23.501534,-47.452594,South America,BRASILE,NaN,GHISIO ERBA STEFANO,Vice Console onorario,NaN,NaN
88,623d88bd7dd56dbed742a0b9,VICE CONSOLATO ONORARIO - SAINT DENIS (Isola d...,11,-20.89066,55.455054,Europe,FRANCIA: TERRITORI AMMINISTRATI IN AFRICA,20 rue de la Compagnie - App. 11 - 1er etage -...,BERTANI NICOLA,Vice Console onorario,NaN,saintdenis.onorario@esteri.it
89,623d88bd7dd56dbed742a101,AGENZIA CONSOLARE ONORARIA - RIO CUARTO (Cordoba),12,-33.1247691,-64.351341,South America,ARGENTINA,Colon 243 - 5800 Rio Cuarto,BARTOCCIONI ALBERTO GUSTAVO,Agente consolare onorario,NaN,agenciaconsular@hotmail.com

6.l'elnco dei consolati presenti in argentina

In [ ]:
result=db.consolati_italiani.find({"paese":"ARGENTINA"})
df = pd.DataFrame(list(result))
df

In [ ]:
result = db.consolati_italiani.aggregate([{"$unwind": "$sede"},
                              {"$match": {"paese": "ARGENTINA"}},
                              {"$project": {"_id": 0, "sede": 1, "paese" :1 }}])

df = pd.DataFrame(list(result))
df

                                                 sede      paese
0                VICE CONSOLATO ONORARIO - CORRIENTES  ARGENTINA
1   AGENZIA CONSOLARE ONORARIA - LAS VARILLAS (Cor...  ARGENTINA
2    CONSOLATO GENERALE - BAHIA BLANCA (Buenos Aires)  ARGENTINA
3                  VICE CONSOLATO ONORARIO - LA RIOJA  ARGENTINA
4          AGENZIA CONSOLARE ONORARIA - PUERTO MADRYN  ARGENTINA
5   AGENZIA CONSOLARE ONORARIA - TANDIL (Buenos Ai...  ARGENTINA
6    VICE CONSOLATO ONORARIO - QUILMES (Buenos Aires)  ARGENTINA
7        VICE CONSOLATO ONORARIO - VIEDMA (Rio Negro)  ARGENTINA
8   AGENZIA CONSOLARE - LOMAS DE ZAMORA (Buenos Ai...  ARGENTINA
9        VICE CONSOLATO ONORARIO - POSADAS (Misiones)  ARGENTINA
10  VICE CONSOLATO ONORARIO - NECOCHEA (Buenos Aires)  ARGENTINA
11                  VICE CONSOLATO ONORARIO - TUCUMAN  ARGENTINA
12               AGENZIA CONSOLARE ONORARIA - RAFAELA  ARGENTINA
13  AGENZIA CONSOLARE ONORARIA - MERCEDES (Buenos ...  ARGENTINA
14           AGENZIA CONSOLARE - MORON (Buenos Aires)  ARGENTINA
15      VICE CONSOLATO ONORARIO - SANTIAGO DEL ESTERO  ARGENTINA
16      VICE CONSOLATO ONORARIO - SAN LUIS (San Luis)  ARGENTINA
17                VICE CONSOLATO ONORARIO - CATAMARCA  ARGENTINA
18        AGENZIA CONSOLARE ONORARIA - VILLA MERCEDES  ARGENTINA
19                  VICE CONSOLATO ONORARIO - FORMOSA  ARGENTINA
20  VICE CONSOLATO ONORARIO - SAN ISIDRO (Buenos A...  ARGENTINA
21                  VICE CONSOLATO ONORARIO - NEUQUEN  ARGENTINA
22  AGENZIA CONSOLARE ONORARIA - OLAVARRIA (Buenos...  ARGENTINA
23             AGENZIA CONSOLARE ONORARIA - CONCORDIA  ARGENTINA
24  AGENZIA CONSOLARE ONORARIA - PERGAMINO (Buenos...  ARGENTINA
25            CONSOLATO GENERALE - ROSARIO (Santa FÃ¨)  ARGENTINA
26                  CONSOLATO GENERALE - BUENOS AIRES  ARGENTINA
27    VICE CONSOLATO ONORARIO - SAN SALVADOR DE JUJUY  ARGENTINA
28      VICE CONSOLATO ONORARIO - RESISTENCIA (Chaco)  ARGENTINA
29  AGENZIA CONSOLARE ONORARIA - SAN FRANCISCO (Co...  ARGENTINA
30                       CONSOLATO GENERALE - CORDOBA  ARGENTINA
31     VICE CONSOLATO ONORARIO - SAN RAFAEL (Mendoza)  ARGENTINA
32             AGENZIA CONSOLARE ONORARIA - EL DORADO  ARGENTINA
33          VICE CONSOLATO ONORARIO - TRES DE FEBRERO  ARGENTINA
34           AGENZIA CONSOLARE ONORARIA - VILLA MARIA  ARGENTINA
35       CONSOLATO GENERALE - LA PLATA (Buenos Aires)  ARGENTINA
36                CONSOLATO DI PRIMA CLASSE - MENDOZA  ARGENTINA
37                    VICE CONSOLATO ONORARIO - SALTA  ARGENTINA
38       VICE CONSOLATO ONORARIO - SANTA ROSA DE TOAY  ARGENTINA
39  AGENZIA CONSOLARE ONORARIA - TRES ARROYOS (Bue...  ARGENTINA
40                          CONSOLATO - MAR DEL PLATA  ARGENTINA
41  AGENZIA CONSOLARE ONORARIA - RIO CUARTO (Cordoba)  ARGENTINA

7.l'elnco dei consolati presenti in argentina e in brasile

In [ ]:
result=db.consolati_italiani.find({"$or":[{"paese":"ARGENTINA"},{"paese": "BRASILE"}]})
df = pd.DataFrame(list(result))
df

,_id,sede,idtiposede,lat,lng,continente,paese,indirizzo,capomissione,funzionecapo,sitoweb,email
0,623d88bd7dd56dbed7429f43,CONSOLATO GENERALE DI PRIMA CLASSE - SAN PAOLO,3,-23.559803,-46.6578951,South America,BRASILE,"Avenida Paulista, 1963 - 01311-300 San Paolo",PALA MICHELE,CONSOLE GENERALE,www.conssanpaolo.esteri.it,segreteria.sanpaolo@esteri.it
1,623d88bd7dd56dbed742a08f,VICE CONSOLATO ONORARIO - CORRIENTES,11,-27.471762,-58.8278205,South America,ARGENTINA,Calle Bolivar n.1839,BRIANTI ROLON CARLOS DOMINGO,Vice Console onorario,NaN,estudiobrianti@gigared.com
2,623d88bd7dd56dbed742a0a6,VICE CONSOLATO ONORARIO - CAMPO GRANDE (Mato G...,11,-20.465283,-54.6179245,South America,BRASILE,"Rua XV de Novembro,253 - Centro - 79002-140 Ca...",TRENTIN ALCIDES,Vice Console onorario,NaN,NaN
3,623d88bd7dd56dbed742a0d8,AGENZIA CONSOLARE ONORARIA - LAS VARILLAS (Cor...,12,-31.8719864,-62.722822,South America,ARGENTINA,Italia 354 - 5940 Las Varillas,LARGHI DOMINGO PAOLO,Agente consolare onorario,NaN,dlarghi@lasvarinet.com.ar
4,623d88bd7dd56dbed742a0e9,AGENZIA CONSOLARE ONORARIA - SAO JOSE' DO RIO ...,12,-20.8204749,-49.3890263,South America,BRASILE,Rua Pernanbuco 3130 - 15015-770 SAO JOSEâ DO R...,SESTINI ALCEU GERMANO,Agente consolare onorario,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
75,623d88bd7dd56dbed742a0e2,AGENZIA CONSOLARE ONORARIA - TRES ARROYOS (Bue...,12,-38.3849172,-60.276027,South America,ARGENTINA,Lavalle 556 - 7500 Tres Arroyos,CENCI GENTILE CAROLINA,Agente consolare onorario,NaN,NaN
76,623d88bd7dd56dbed7429f69,CONSOLATO GENERALE - CURITIBA (ParanÃ ),4,-25.4283563,-49.2732515,South America,BRASILE,"Rua Marechal Deodoro, 630 - 21Â°Andar-Centro C...",FESTA RAFFAELE,CONSOLE GENERALE,www.conscuritiba.esteri.it,segreteria.curitiba@esteri.it
77,623d88bd7dd56dbed7429f8f,CONSOLATO - MAR DEL PLATA,6,-38.0111432,-57.5395984,South America,ARGENTINA,Falucho 1416 - 7600 Mar del Plata,CORTESE DARIO,CONSOLE,www.consmardelplata.esteri.it,segreteria.mardelplata@esteri.it
78,623d88bd7dd56dbed742a04a,VICE CONSOLATO ONORARIO - SOROCABA,11,-23.501534,-47.452594,South America,BRASILE,NaN,GHISIO ERBA STEFANO,Vice Console onorario,NaN,NaN
79,623d88bd7dd56dbed742a101,AGENZIA CONSOLARE ONORARIA - RIO CUARTO (Cordoba),12,-33.1247691,-64.351341,South America,ARGENTINA,Colon 243 - 5800 Rio Cuarto,BARTOCCIONI ALBERTO GUSTAVO,Agente consolare onorario,NaN,agenciaconsular@hotmail.com

In [ ]:
result = db.consolati_italiani.aggregate([{"$unwind": "$sede"},
                              {"$match": {"paese": "ARGENTINA","paese": "BRASILE"}},
                              {"$project": {"_id": 0, "sede": 1, "paese" :1 }}])

df = pd.DataFrame(list(result))
df

8.i consolati di cui non si conosce il sito web

In [ ]:
result=db.consolati_italiani.find({},{"sitoweb": None})
df = pd.DataFrame(list(result))
df

                          _id sitoweb
0    623d88bd7dd56dbed7429f53    None
1    623d88bd7dd56dbed7429f5a    None
2    623d88bd7dd56dbed7429f44    None
3    623d88bd7dd56dbed7429f50    None
4    623d88bd7dd56dbed7429f52    None
..                        ...     ...
446  623d88bd7dd56dbed742a0d2    None
447  623d88bd7dd56dbed742a0d3    None
448  623d88bd7dd56dbed742a0e4    None
449  623d88bd7dd56dbed742a0eb    None
450  623d88bd7dd56dbed742a101    None

[451 rows x 2 columns]

In [ ]:
result = db.consolati_italiani.aggregate([{"$unwind": "$sede"},
                              { "sitoweb": { "$nin": [ "" ] }},
                              {"$project": {"_id": 0, "sede": 1, "sitoweb" :1 }}])

df = pd.DataFrame(list(result))
df

OperationFailure: ignored

9.i consolati che non hanno una mail del Ministero degli Esteri

In [ ]:
result=db.consolati_italiani.find({"email":{"$not":{"$regex":"@esteri.it"}}})
df = pd.DataFrame(list(result))
df

,_id,sede,idtiposede,continente,paese,indirizzo,capomissione,funzionecapo,email,lat,lng,sitoweb
0,623d88bd7dd56dbed742a00b,CONSOLATO ONORARIO - HAIFA,10,Asia,ISRAELE,"Sderot Hanasi St. 40 - 34643 Haifa, Israele",GROSS CARLO,Console onorario,carlogross@bezeqint.net,NaN,NaN,NaN
1,623d88bd7dd56dbed742a035,CONSOLATO ONORARIO - BELFAST (Antrim),10,Europe,REGNO UNITO,"42 Glenholm Drive, BT9 6LW",FERRIERI FEDERICA,Console onorario,leo@dagostino42.fsnet.co.uk,54.719534,-6.20725,NaN
2,623d88bd7dd56dbed742a059,VICE CONSOLATO ONORARIO - BEERSHEVA,11,Asia,ISRAELE,NaN,SZTORCHAIN BLIMA,Vice Console onorario,NaN,31.046051,34.851612,NaN
3,623d88bd7dd56dbed742a06a,VICE CONSOLATO ONORARIO - WINDSOR (Ontario),11,Northern America,CANADA,"635, Erie Street East - Windsor (Ontario) N9A 3Y1",DI SALVO LORENZO MARIO DOMENICO,Vice Console onorario,NaN,NaN,NaN,NaN
4,623d88bd7dd56dbed742a08f,VICE CONSOLATO ONORARIO - CORRIENTES,11,South America,ARGENTINA,Calle Bolivar n.1839,BRIANTI ROLON CARLOS DOMINGO,Vice Console onorario,estudiobrianti@gigared.com,-27.471762,-58.8278205,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
241,623d88bd7dd56dbed742a0a8,VICE CONSOLATO ONORARIO - COPIAPO' (Atacama),11,South America,CILE,vacante,ALBASINI PAOLO,Vice Console onorario,NaN,NaN,NaN,NaN
242,623d88bd7dd56dbed742a0d2,AGENZIA CONSOLARE ONORARIA - CEFALONIA,12,Europe,GRECIA,Od. Stavrou Metaxa 21 - 28100 - ARGOSTOLI,MICHELETTI GRAZIELLA,Agente consolare onorario,gratsiel@otenet.gr,38.178011,20.4886002,NaN
243,623d88bd7dd56dbed742a0d3,AGENZIA CONSOLARE ONORARIA - SANTORINI,12,Europe,GRECIA,"Messaria, Santorini",PAGONA REKAITI MARIA,Agente consolare onorario,pamaria@rekaiti.gr,36.3990884,25.4477265,NaN
244,623d88bd7dd56dbed742a0eb,AGENZIA CONSOLARE ONORARIA - BARINAS,12,South America,VENEZUELA,"c/c Club Italo Venezolano, Av. 23 de Enero, fr...",GHERARDI PALANGE GIUSEPPE,Agente consolare onorario,gherardip@gmail.com,NaN,NaN,NaN
245,623d88bd7dd56dbed742a101,AGENZIA CONSOLARE ONORARIA - RIO CUARTO (Cordoba),12,South America,ARGENTINA,Colon 243 - 5800 Rio Cuarto,BARTOCCIONI ALBERTO GUSTAVO,Agente consolare onorario,agenciaconsular@hotmail.com,-33.1247691,-64.351341,NaN

10.il numero di consolati in ogni continente

In [ ]:
result = db.consolati_italiani.aggregate([
                {"$group" : {"_id": "$continente", "total" : {"$sum" : 1}}},
                { "$sort": {"_id": 1 }}
                ])
df = pd.DataFrame(list(result))
df

                _id  total
0            Africa     31
1              Asia     49
2            Europe    160
3  Northern America     63
4           Oceania     15
5     South America    133

In [ ]:
result = db.consolati_italiani.aggregate([{ "$unwind": "$continente" },
                              { "$group" : {"_id": "$continente", "total" : {"$sum" : 1}}},
                              { "$project": {"_id": 0,"continente": "$_id","total": "$total"}}])
df = pd.DataFrame(list(result))
df

esercizio 11 i continenti che hanno piÃ¹ di 50 consolati. Ordinare in ordine decrescente a partire dal continente che ha piÃ¹ consolati

In [ ]:
result = db.consolati_italiani.aggregate([
                {"$group" : {"_id": "$continente", "total" : {"$sum" : 1}}},
                {"$match":{"total":{"$gt":50}}},
                { "$sort": {"total": -1 }}
                ])
df = pd.DataFrame(list(result))
df

                _id  total
0            Europe    160
1     South America    133
2  Northern America     63

In [ ]:
result = db.consolati_italiani.aggregate([{ "$unwind": "$continente" },
                              { "$group" : {"_id": "$continente", "total" : {"$sum" : 1}}},
                              { "$match": { "total": { "$gt": 50 }}},
                              { "$sort": {"total": -1 }},
                              { "$project": {"_id": 0,"continente": "$_id","total": "$total"}}])
df = pd.DataFrame(list(result))
df

esrcizio 12 il paese che ha piÃ¹ consolati

In [ ]:
result = db.consolati_italiani.aggregate([{ "$unwind": "$continente" },
                              { "$group" : {"_id": "$continente", "total" : {"$sum" : 1}}},
                              { "$match": { "total": { "$gt": 50 }}},
                              { "$sort": {"total": -1 }},
                              { "$project": {"_id": 0,"continente": "$_id","total": "$total"}}])
df = pd.DataFrame(list(result))
df.head(1)